'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from "react";
import dynamic from "next/dynamic";

import EVENTPHOTO from "@/assets/events/azientek.jpg";

// Dynamically import EventNotification to avoid hydration issues
const EventNotification = dynamic(() => import("@/components/EventNotification"), {
  ssr: false,
  loading: () => null
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const event = {
    id: "iosc-edc-gitTogether",
    title: "IoSC‑EDC GitTogether 2025",
    description:
      "Week long, hands on open source collaboration competition!",
    date: "Aug 23–24, 2025 • Online",
    ctaUrl: "/eventPage",
    image: EVENTPHOTO,
    neverShowAgainDays: 30,
  };

  return (
    <html lang="en">
      <head>
        <title>IoSC-EDC</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        {isClient && <EventNotification 
        // event={event} 
        position="bottom-center" />}
      </body>
    </html>
  );
}